### ISSUE TITLE
Creating index on Azure Cosmos DB not working

### ISSUE THREAD

**Issue by soderluk** [cocreators-ee/migrate-anything#2]
Need to be able to determine if the MongoDB database is created with a partition key or not. When running migrate-anything on e.g. Azure CosmosDB in MongoDB compatibility mode, we get `pymongo.errors.OperationFailure: Shared throughput collection should have a partition key` when trying to create the migration collection and it's index in `__init__.py`

**Comment by lietu** [comment]
Since this is not universal, it could maybe be done via some optional `init_fn` argument, which then could be written to detect if it's running on Cosmos DB and then run the collection creation in a way required for proper operation there.

**Comment by EliuX** [comment]
I think that the problem you are having is more related to the use of the python library for cosmos db. Try doing something like:
```
from azure.cosmos import PartitionKey
db = client.get_database_client(db_id)
db.create_container({
        'id': 'persons',
        'partition_key': PartitionKey(path='/company_id'),
        'unique_key_policy': {
            'uniqueKeys': [
                {'paths': ['/email']},
            ]
        }
})
```
For creating a [partition key](https://stackoverflow.com/questions/45067692/azure-cosmos-db-understanding-partition-key) you need to import `PartitionKey`.

**Comment by soderluk** [comment]
@EliuX Thanks for your input! That certainly helped. Now the issue is that whenever I create a new document, it complains that `document does not contain shard key` even though we add the `_id` in the payload. The `partition_key` being `PartitionKey(path="/_id")`. Any ideas?

**Comment by EliuX** [comment]
Hi @soderluk, well, I never specified the `_id` as the partition key, although it seems to comply the requirements for [choosing a partition key](https://docs.microsoft.com/en-us/azure/cosmos-db/partitioning-overview#choose-partitionkey).  I choose to use the type of attribute that does not change in an item and it works well in combination with the unique keys.
I wonder which is your container definition for the collections to track the migrations. I used in a project something like
```
        migrations_definition = {
            'id': "migration",
            'partition_key': PartitionKey(path='/ctx_id'),
            'unique_key_policy': {
                'uniqueKeys': [
                    {'paths': ['/name']},
                ]
            }
        }
```
In the constructor of the `Storage` class for **CosmosDB**, I create the container if it not existed. By using `ctx_id` as the partition key I was able to use the same `migration` collection for different contexts using the same database/collection. 

Each document must have an `_id` field, which I autogenerated using the [UUID version 4 for Python](https://docs.python.org/3/library/uuid.html#uuid.uuid4). Also an `id` field is required, so I chose to use the same value I used for the `name`.

I hope this helps you and any other advice in this [stackoverflow question](https://stackoverflow.com/questions/45587691/comosdb-mongoapi-document-does-not-contain-shard-key).

**Comment by soderluk** [comment]
Hi @EliuX, after some more extensive investigations, and getting some really weird results from the command `az cosmosdb mongodb collection show` namely this:
```
"shardKey": {
  "Invalid path, please contact support": "Hash"
}
```
I tried out the solution to add `/'$v'/_id/'$v'` from this suggestion: https://github.com/Azure/azure-cli/issues/8633#issuecomment-475294283 and it seems to have fixed the issue about inserting records.

Now I just wonder, what is this `$v` thing?

I'll close this issue now, since there is no need to do any customizations after all.
